/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'gestion-ruta': RouteRecordInfo<'gestion-ruta', '/gestion-ruta', Record<never, never>, Record<never, never>>,
    'gestion-ruta-components-tabla-detalle-ruta-programacion': RouteRecordInfo<'gestion-ruta-components-tabla-detalle-ruta-programacion', '/gestion-ruta/components/tabla-detalle-ruta-programacion', Record<never, never>, Record<never, never>>,
    'gestion-ruta-components-tabla-programaciones': RouteRecordInfo<'gestion-ruta-components-tabla-programaciones', '/gestion-ruta/components/tabla-programaciones', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna': RouteRecordInfo<'intermodal-base-interna', '/intermodal-base-interna', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog': RouteRecordInfo<'intermodal-base-interna-components-dialog', '/intermodal-base-interna/components/dialog', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog-asignar': RouteRecordInfo<'intermodal-base-interna-components-dialog-asignar', '/intermodal-base-interna/components/DialogAsignar', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog-diseño': RouteRecordInfo<'intermodal-base-interna-components-dialog-diseño', '/intermodal-base-interna/components/DialogDiseño', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog-distancia': RouteRecordInfo<'intermodal-base-interna-components-dialog-distancia', '/intermodal-base-interna/components/dialogDistancia', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog-editar-proyecto': RouteRecordInfo<'intermodal-base-interna-components-dialog-editar-proyecto', '/intermodal-base-interna/components/DialogEditarProyecto', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog-estado-avance': RouteRecordInfo<'intermodal-base-interna-components-dialog-estado-avance', '/intermodal-base-interna/components/dialogEstadoAvance', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog-fechas-operativa': RouteRecordInfo<'intermodal-base-interna-components-dialog-fechas-operativa', '/intermodal-base-interna/components/dialogFechasOperativa', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dialog-trabajos': RouteRecordInfo<'intermodal-base-interna-components-dialog-trabajos', '/intermodal-base-interna/components/DialogTrabajos', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-dynamic-state-input': RouteRecordInfo<'intermodal-base-interna-components-dynamic-state-input', '/intermodal-base-interna/components/DynamicStateInput', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-form-capex': RouteRecordInfo<'intermodal-base-interna-components-form-capex', '/intermodal-base-interna/components/FormCapex', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-form-diseno': RouteRecordInfo<'intermodal-base-interna-components-form-diseno', '/intermodal-base-interna/components/FormDiseno', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-form-integracion': RouteRecordInfo<'intermodal-base-interna-components-form-integracion', '/intermodal-base-interna/components/FormIntegracion', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-form-pex': RouteRecordInfo<'intermodal-base-interna-components-form-pex', '/intermodal-base-interna/components/FormPex', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-form-proyecto': RouteRecordInfo<'intermodal-base-interna-components-form-proyecto', '/intermodal-base-interna/components/FormProyecto', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-form-trabajos': RouteRecordInfo<'intermodal-base-interna-components-form-trabajos', '/intermodal-base-interna/components/FormTrabajos', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-components-tabla': RouteRecordInfo<'intermodal-base-interna-components-tabla', '/intermodal-base-interna/components/tabla', Record<never, never>, Record<never, never>>,
    'intermodal-base-interna-dialog-asignar': RouteRecordInfo<'intermodal-base-interna-dialog-asignar', '/intermodal-base-interna/DialogAsignar', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'preasignacion': RouteRecordInfo<'preasignacion', '/preasignacion', Record<never, never>, Record<never, never>>,
    'programacion': RouteRecordInfo<'programacion', '/programacion', Record<never, never>, Record<never, never>>,
    'programacion-components-modal-generar': RouteRecordInfo<'programacion-components-modal-generar', '/programacion/components/modal_generar', Record<never, never>, Record<never, never>>,
    'programacion-components-planificador-sidebar': RouteRecordInfo<'programacion-components-planificador-sidebar', '/programacion/components/PlanificadorSidebar', Record<never, never>, Record<never, never>>,
    'programacion-components-tablaprogramacion': RouteRecordInfo<'programacion-components-tablaprogramacion', '/programacion/components/tablaprogramacion', Record<never, never>, Record<never, never>>,
    'programacion-components-zona-card': RouteRecordInfo<'programacion-components-zona-card', '/programacion/components/ZonaCard', Record<never, never>, Record<never, never>>,
    'programacion-ver': RouteRecordInfo<'programacion-ver', '/programacion-ver', Record<never, never>, Record<never, never>>,
    'reasignacion': RouteRecordInfo<'reasignacion', '/reasignacion', Record<never, never>, Record<never, never>>,
    'reasignacion-components-dialog-registro': RouteRecordInfo<'reasignacion-components-dialog-registro', '/reasignacion/components/dialogRegistro', Record<never, never>, Record<never, never>>,
    'reasignacion-components-tabla': RouteRecordInfo<'reasignacion-components-tabla', '/reasignacion/components/tabla', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'seguimiento-ftth': RouteRecordInfo<'seguimiento-ftth', '/seguimiento-ftth', Record<never, never>, Record<never, never>>,
    'seguimiento-ftth-components-card-seguimiento': RouteRecordInfo<'seguimiento-ftth-components-card-seguimiento', '/seguimiento-ftth/components/card_seguimiento', Record<never, never>, Record<never, never>>,
    'seguimiento-ftth-components-dialog-registrar-avance': RouteRecordInfo<'seguimiento-ftth-components-dialog-registrar-avance', '/seguimiento-ftth/components/DialogRegistrarAvance', Record<never, never>, Record<never, never>>,
    'seguimiento-ftth-components-tabla': RouteRecordInfo<'seguimiento-ftth-components-tabla', '/seguimiento-ftth/components/tabla', Record<never, never>, Record<never, never>>,
    'trabajos-inspecciones': RouteRecordInfo<'trabajos-inspecciones', '/trabajos-inspecciones', Record<never, never>, Record<never, never>>,
    'trabajos-timbrados': RouteRecordInfo<'trabajos-timbrados', '/trabajos-timbrados', Record<never, never>, Record<never, never>>,
    'trabajos-timbrados-components-date-selector': RouteRecordInfo<'trabajos-timbrados-components-date-selector', '/trabajos-timbrados/components/dateSelector', Record<never, never>, Record<never, never>>,
    'trabajos-timbrados-components-result-dialog': RouteRecordInfo<'trabajos-timbrados-components-result-dialog', '/trabajos-timbrados/components/ResultDialog', Record<never, never>, Record<never, never>>,
  }
}
